### ISSUE TITLE
Floor is not defined

### ISSUE THREAD

**Issue by malinin13** [magwo/elevatorsaga#36]
Can't continue the game because of this problem. 
 There is a problem with your code: ReferenceError: floor is not defined
at Object.eval (eval at (http://play.elevatorsaga.com/app.js:68:35), :8:13)
at Object.el.trigger (http://play.elevatorsaga.com/libs/riot.js:45:12)
at Object.elevatorInterface.checkDestinationQueue (http://play.elevatorsaga.com/interfaces.js:15:35)
at http://play.elevatorsaga.com/world.js:168:64
at Function.St (http://play.elevatorsaga.com/libs/lodash.min.js:23:147)
at Object.world.init (http://play.elevatorsaga.com/world.js:168:15)
at updater (http://play.elevatorsaga.com/world.js:194:31)

**Comment by Envek** [comment]
Please provide your code, nothing can be said without it.

**Comment by malinin13** [comment]
http://prntscr.com/5x0z47

{
    init: function(elevators, floors) {
        var elevator = elevators[0]; // Let's use the first elevator
        elevator.on("idle", function() {
            // The elevator is idle, so let's go to all the floors (or did we forget one?)
            elevator.goToFloor(0);
            elevator.goToFloor(1);
            floor.on("up_button_pressed", function(event) { 
                alert('ololo');
            } );
        });
       
    },
    update: function(dt, elevators, floors) {
        // We normally don't need to do anything here
    }
}

**Comment by marado** [comment]
You don't have a 'floor' object.

**Comment by marado** [comment]
You can see a working example here:https://github.com/marado/elevator-saga-solutions/blob/d8153339ba8bd0cc751d9e8670b401534bcd4b24/code.js
